variables:
  # custom runner for group 9 team project
  GITLAB_RUNNER = "group_nine_runner"

image: maven:latest

# stages defined to test, then build and deploy the application on render.com
stages:
  - test
  - build
  - deploy

test:
  stage: test
  tags:
    - $GITLAB_RUNNER
  script:
  # this will clean the target folder and then test the maven project
    - mvn clean test

build:
  stage: build
  tags:
    - $GITLAB_RUNNER
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  tags:
    - $GITLAB_RUNNER
  script:
    - echo "Deploy to test server on render"
    - curl -s "$RENDER_TRIGGER_URL_TEST_ENV"
  only:
    - main