local_docker_build:
  image: docker:dind
  stage: docker_build
  tags:
    - grp09_test1
  script:
    - docker info
    - docker build -t $IMAGE_NAME .
    - docker save $IMAGE_NAME > $IMAGE_NAME.tar
  artifacts:
    paths:
      - $IMAGE_NAME.tar