image: maven:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - mvn clean install

deploy:
  stage: deploy
  script:
    - echo "Deploy to production server"
    - curl -s "https://api.render.com/deploy/srv-ci2ptt67avj2t359mss0?key=_AyLa8MCgPg"
  only:
    - main