image: maven:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - mvn clean install

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y wget
    - wget -qO- https://deb.nodesource.com/setup_12.x | bash -
    - apt-get install -y nodejs
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_TOKEN
    - firebase deploy --token $FIREBASE_TOKEN --only hosting  
  only:
    - main